anchor_version = "0.28.0"


[programs.localnet]
rfq = "FqAhTZg86EKEzeWMLtutVDRXJuLWrey7oDHr3Au6RFdo"
risk_engine = "CtfTi4TstqJaxEh8giQ7kK8CKXsJyF9CuwdcVoqGrEi1"
spot_instrument = "BMXWVaYPVJ4G8g2MMJt51CDgjHHuoirPMvsTUadv3s3v"
psyoptions_european_instrument = "4KC8MQi2zQGr7LhTCVTMhbKuP4KcpTmdZjxsDBWrTSVf"
psyoptions_american_instrument = "HpmyVA3t3uNGgdx86AuwZww7gnAWB57vepnk3732vEr9"
hxro_print_trade_provider = "598ZWckNjupx5sftmNC27NPRYHbwNbxi2dYBUan7Su1P"
vault_operator = "DftT8Q74YPqwrtJzy6g97XLzouG2YWaWZfRad6yK2GvA"

[programs.devnet]
rfq = "FqAhTZg86EKEzeWMLtutVDRXJuLWrey7oDHr3Au6RFdo"
risk_engine = "CtfTi4TstqJaxEh8giQ7kK8CKXsJyF9CuwdcVoqGrEi1"
spot_instrument = "BMXWVaYPVJ4G8g2MMJt51CDgjHHuoirPMvsTUadv3s3v"
psyoptions_european_instrument = "4KC8MQi2zQGr7LhTCVTMhbKuP4KcpTmdZjxsDBWrTSVf"
psyoptions_american_instrument = "HpmyVA3t3uNGgdx86AuwZww7gnAWB57vepnk3732vEr9"
hxro_print_trade_provider = "598ZWckNjupx5sftmNC27NPRYHbwNbxi2dYBUan7Su1P"
vault_operator = "DftT8Q74YPqwrtJzy6g97XLzouG2YWaWZfRad6yK2GvA"

[programs.mainnet]
rfq = "FqAhTZg86EKEzeWMLtutVDRXJuLWrey7oDHr3Au6RFdo"
risk_engine = "CtfTi4TstqJaxEh8giQ7kK8CKXsJyF9CuwdcVoqGrEi1"
spot_instrument = "BMXWVaYPVJ4G8g2MMJt51CDgjHHuoirPMvsTUadv3s3v"
psyoptions_european_instrument = "4KC8MQi2zQGr7LhTCVTMhbKuP4KcpTmdZjxsDBWrTSVf"
psyoptions_american_instrument = "HpmyVA3t3uNGgdx86AuwZww7gnAWB57vepnk3732vEr9"
hxro_print_trade_provider = "598ZWckNjupx5sftmNC27NPRYHbwNbxi2dYBUan7Su1P"
vault_operator = "DftT8Q74YPqwrtJzy6g97XLzouG2YWaWZfRad6yK2GvA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "rfq/program",
    "risk-engine/program",
    "spot-instrument/program",
    "psyoptions-european-instrument/program",
    "hxro-print-trade-provider/program",
    "psyoptions-american-instrument/program",
    "vault-operator/program",
]

[scripts]
generate-test-fixtures = "yarn ts-node -T tests/scripts/fixturesGenerator.ts"
