name: Run Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x", "18.x"]
        solana: ["1.14.12"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache build artefacts
        uses: Swatinem/rust-cache@v2.2.1
        with:
          cache-on-failure: 'true'

      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.28.0 anchor-cli --locked

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ matrix.solana }}

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Check Cargo fmt
        continue-on-error: false
        shell: bash
        run: cargo fmt --check

      - name: Check cargo clippy
        run: cargo clippy

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint TypeScript
        continue-on-error: false
        shell: bash
        run: yarn lint:check

      - name: Build
        run: anchor build

      - name: Run tests
        continue-on-error: false
        shell: bash
        run: anchor test --skip-build
